### PR TITLE
Let's prove Python!

### PR DESCRIPTION
**Pull request by Zac-HD**
Because [even Python can join the fun](https://twitter.com/hillelogram/status/1228925803464929280)!

I spend most of my time with Hypothesis generating counterexamples, so it's especially nice to see that sometimes you can be sure there aren't any (assuming that your library works as modelled, which IME it probably doesn't...)

And because CrossHair deserves more love and exposure 😁

### CODE REVIEW

**Comment by hwayne** [comment]
Ahahaha this is great

**Comment by Zac-HD** [comment]
I know right! So short! So rigorous! *And it's Python!*

You can do anything in this language, I love it. This is admittedly the best since the [`inlinec` codec](https://github.com/georgek42/inlinec) hack, and at least to me more useful...

**Comment by Kha** [comment]
This is super cool. However, it's not clear to me whether CrossHair is actually (supposed to be) sound or not. The ~~last~~ second-to-last point of https://github.com/pschanely/CrossHair#limitations makes it sound like soundness is not a goal, so I suppose this is more "probably-correct Python" than "provably-correct"? Still impressive.

**Comment by Zac-HD** [comment]
> Be aware that the absence of a counterexample does not guarantee that the property holds.

As I understand it this is mostly because there's no way to verify that the translation to SAT formulae is sound, or that CPython is behaving as expected (vs eg ctypes hacks modifying the interpreter), and of course there's not actually a spec for Python - just a reference implementation which nonetheless has bugs!

But I will go back and check whether "approximately sound" is a design goal, and suggest that undecided propositions at least not pass silently if that's the current behavior.

**Comment by pschanely** [comment]
Yeah, it's unsound for the reasons that Zac mentions and more; I wouldn't call CrossHair a verification tool, and think we should add some sort of note that this entry is cheating. 😀 I'm happy to write something up!

The major thing I'd want to make clear is that the tool is very incomplete, and collapses the "unknown" and "confirmed" states before generating output(*). The incompleteness comes from the fact that only individual execution paths are proven and all nontrivial code has an infinite number of execution paths. (even this implementation of leftpad!) The approach works pretty well in practice (it avoids dealing with quantifiers, which IMO are the mortal enemy of the SMT solver), but makes CrossHair much more of a counterexample-finder than a verification tool.

(*) I'd made this decision for "product" reasons but am not fully committed to it. I'll wait for Zac to file a CrossHair bug and get into the details there.  😀

**Pull request merged**
