### PR TITLE
[ new ] agda sol in correct-by-construction style

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by hwayne** [comment]
Hiya! Trying to make sure I understand this: the idea is that you're using the specification to construct a function satisfying it, right? Would the proof be invalid if I instead wrote `Padded : ∀ k → LeftPad xs (k + n) (xs ++ replicate {n = k} x)`, aka a right-pad?

**Comment by gallais** [comment]
You're right that `rightpad` would have a very close specification (although it'd
have to use `n + k` as a return index rather than `k + n` to typecheck because
of the return type of vector concatenation):

```agda
data RightPad {n : ℕ} (xs : Vec A n) : ∀ m → Vec A m → Set where
  Padded : ∀ k → RightPad xs (n + k) (xs ++ replicate {n = k} x)
```

The `leftpad` proof wouldn't go through because `LeOrGt` is left-biased. It provides
evidence that `m` is smaller than `n` by deconstructing `n` into `k + m` for some k.
But to be able to pad an `xs` of length `n` on the right we need to break down `m ⊔ n`
into an `n + k` shape rather than a `k + n` one.

**Comment by hwayne** [comment]
Gotcha. One last question: the reason I can't write `Padded : ∀ k → LeftPad xs (k + n) (replicate {n = k} "a" ++ xs)` is because `module _ {a} {A : Set a} (x : A)` means it won't typecheck, right?

**Comment by gallais** [comment]
Yes, I have put both the type of "character" and the one character to use for padding
as parameters of the problem.

The `module _` part means that the module is anonymous: it doesn't have a name and
is immediately opened once its scope ends. This is effectively a way of adding the same
set of parameters to all of the definitions in that scope.

**Comment by hwayne** [comment]
Awesome, thank you for explaining!

**Pull request merged**
