### PR TITLE
Merge a Coq solution.

### PR DESCRIPTION
**Pull request by ezrakilty**
This is my contribution, as discussed!

### CODE REVIEW

**Comment by hwayne** [comment]
Thanks so much for doing this! One request: could you revise the readme.md to be more in line with the convention? Specifically, it should link to where the reader can find out more about Coq, and it should explain what Coq is outside the context of the Leftpad challenge. I expect that for a lot of people, this repo is going to be their first introduction to a lot of these tools, which is why I think it's important that the readmes explain what the languages are. See the [Isabelle](https://github.com/hwayne/lets-prove-leftpad/blob/master/isabelle/readme.md) example as a rough template. 

Also, you're welcome to include some shilling of your stuff if you want =)

**Comment by ezrakilty** [comment]
Absolutely. Great comments. I've posted some README updates that I'll do another pull request for. Not sure I went as far as you have in mind—let me know if not.

**Comment by ezrakilty** [comment]
wut

**Comment by hwayne** [comment]
chicken butt

**Pull request merged**
