### PR TITLE
Lean solution: WIP

### PR DESCRIPTION
**Pull request by cipher1024**
I still have to fill in an explanation of the proof but if there's anything else to fix, I'd like to know. Thanks!

### CODE REVIEW

**Comment by hwayne** [comment]
Everything looks good so far! For the explanation, you don't need to explain `unique`, just leftpad.

**Comment by hwayne** [comment]
Pokadoke!

**Comment by cipher1024** [comment]
I beg your pardon?

**Comment by hwayne** [comment]
Oh, sorry, yeah that probably made zero sense. Okay, in full English:

Heya! Are you still interested in contributing an explanation of the Leftpad? No worries if not, I'll just close the PR in that case. Otherwise, just get it in whenever you have the time and we can merge this proof in!

**Comment by cipher1024** [comment]
Haha! I like the result of `unfold pokadoke` better.

Thanks for the reminder! It got buried under way too many projects. I'll try to wrap it up quickly. Do you have a planned use for this project? A paper for example?

**Comment by hwayne** [comment]
Nope, I just made it as a public reference for people. Take as much time as you need =)

**Comment by cipher1024** [comment]
Thanks for organizing this challenge by the way :) ... and putting it back on my radar

**Comment by hwayne** [comment]
Going to close this because #29 added a full version of Lean. Nonetheless, thanks for your help!

**Comment by cipher1024** [comment]
Sorry I left you hanging so long. Glad we could get a good solution though

**Pull request closed without merging**
