### PR TITLE
Rust type-level proof, sort-of

### PR DESCRIPTION
**Pull request by JohnDowson**
I believe this is as close as you can get to proving a left-pad in pure rust.
Although I think many may disagree the provided implementation of left-pad actually does left-padding.

### CODE REVIEW

**Comment by hwayne** [comment]
Wow coming late to this, sorry. Can you walk me through how it proves all three properties? I'm not familiar enough with Rust to sight-read this.

**Comment by JohnDowson** [comment]
Well, it doesn't really. It really only proves that padding is correct, and that overall length is correct, but not that the `"hello"` part stays the same.

You could go further, building fully type-level string, but I couldn't quite figure out a way to pad that version.

**Comment by hwayne** [comment]
I'm afraid I can't accept it then. But I think explaining what you were able to do would make a really interesting blog post on its own!

(I really need to create a compendium of near-misses, don't I)

**Comment by JohnDowson** [comment]
> I'm afraid I can't accept it then. But I think explaining what you were able to do would make a really interesting blog post on its own!
I'm moreso hoping somebody better versed in type magic might see this and give a tip on how to fully prove it with a sort of Peano string.

**Pull request closed without merging**
