### PR TITLE
Clojure implementation

### PR DESCRIPTION
**Pull request by bmaddy**
Hi @hwayne, here's a Clojure implementation. Please let me know if there's anything you would like changed. Thanks!

### CODE REVIEW

**Comment by hwayne** [comment]
Thanks for submitting this! Unfortunately, I can't accept it: property-based testing isn't a formal proof of correctness. Consider a function that satisfied the specs _except_ if you passed in "asdjn356kjn!$#lyn?/??": it would pass PBT, but a theorem prover would catch it.

Nonetheless this is incredibly well-written and you should def turn it into a blog post. Thanks again!

**Comment by bmaddy** [comment]
Is there any chance you'd be willing to tell me where my logic went astray?

From this thread I concluded that Clojure spec was a contract system:
https://twitter.com/hillelogram/status/1068934608618696704

And from this post I concluded that contracts systems are a type of formal verification:
https://hillelwayne.com/post/why-dont-people-use-formal-methods/
(item number 2, just after "Code specs fall into three major camps")

To be clear, I'm not trying to nit pick any comments you've made (you clearly know more about this stuff than me!). I'm just trying to understand so I can get my terms right and learn.

Is it that Clojure spec is a contract system, but not all contract systems do formal verification?

**Comment by hwayne** [comment]
In the parlance of the article, contracts are a means of _code specification_. They express properties of the system, but don't necessarily enforce how they are satisfied. To do that we pair them with some sort of verification system. For almost all languages with contracts, we verify them at runtime: every time the function is called, we check all of the contracts, and if any are false we raise an error.

To be considered a proof, the verification system must show that the contracts are always satisfied, for all possible inputs. Most of the entries that use contracts here, like Dafny and SPARK, do this by shelling out to an SMT solver like Z3. If the implementation was incorrect, Z3 wouldn't be able to 'solve' the contracts, and so it wouldn't be proven correct.

It should be possible to build a formal verification backend for clojure/spec, so you can take a set of specs and prove they're always correct. If that was done, then it would totes fit in there. OTOH, this uses PBT to do informal verification, which is probably better in 99% of cases but means it doesn't work here.

**Comment by bmaddy** [comment]
Sounds good. I've certainly learned something and now have new topics to explore. Thank you so much for your time and thoughtful response--I appreciate it!

**Pull request closed without merging**
