### PR TITLE
LiquidHaskell entry

### PR DESCRIPTION
**Pull request by ranjitjhala**
Hi @hwayne -- here's a PR with the LH entry, edited from a post up at 

https://ucsd-progsys.github.io/liquidhaskell-blog/2018/05/17/hillel-verifier-rodeo-I-leftpad.lhs/

Thanks!

Ranjit.

### CODE REVIEW

**Comment by hwayne** [comment]
Content reported for being _amazing_

What do you think of the idea of making LeftPad.lhs 'just' the code and moving the literate explanation to the Readme or a separete lhs file? I think that would be clearer for layfolk reading the code, but I'm basing that entirely off how Github is rendering the file (and don't know what's considered idiomatic for sharing LH code).

**Comment by ranjitjhala** [comment]
Thanks! Yes I can do that, will update PR tomorrow!

**Comment by ranjitjhala** [comment]
Hi @hwayne -- I converted the .lhs into a .hs file and moved the commentary into the readme. What do you think? Best! Ranjit.

**Comment by hwayne** [comment]
Looks fantastic. Thank you!

**Pull request merged**
