### PR TITLE
Add Metamath

### PR DESCRIPTION
**Pull request by tirix**
See [metamath#3344](https://github.com/metamath/set.mm/issues/3344) for more discussions about what went into this.

### CODE REVIEW

**Comment by hwayne** [comment]
Ah, this is a delight! And I love how you include the whole convo of how it developed :)

I just have one question. When you have something like

```
 ( vl vc vw cc0 cv cmin co cfzo cconcat cn0 cvv wceq chash cfv clpad cmpt2
      csn cxp cmpt df-lpad wa simprr fveq2d oveq2d simprl sneqd xpeq12d oveq12d
      mpteq2dv elexd cword wcel nn0ex mptexd ovmpt2d simpr oveq1d xpeq1d fvmptd
      a1i ovexd ) AIDLIMZEUAUBZNOZPOZBUEZUFZEQOZLDVKNOZPOZVNUFZEQORBEUCOSAJKBES
      SIRLVJKMZUAUBZNOZPOZJMZUEZUFZVTQOZUGZIRVPUGUCSUCJKSSWHUDTAKJIUHVHAWDBTZVT
      ETZUIUIZIRWGVPWKWFVOVTEQWKWCVMWEVNWKWBVLLPWKWAVKVJNWKVTEUAAWIWJUJUKULULWK
      WDBAWIWJUMUNUOAWIWJUJUPUQABCHURAECUSGURAIRVPSRSUTAVAVHVBVCAVJDTZUIZVOVSEQ
      WMVMVRVNWMVLVQLPWMVJDVKNAWLVDVEULVFVEFAVSEQVIVG $.
```

What's the part (in parenthesis) for, and what's ALLCAPSLETTERS part for? I don't need an explanation for what they're doing in every single function, or even a comprehensive explanation for one function, just a quick outline of what role each of them plays in the metamath code. Either put that in a comment or the main descriptor and we're good to go :)

**Comment by tirix** [comment]
Sure! That actually represents the full proof, in a compressed format. The first part, in parentheses, are the axioms and theorems applied, and the second part, in all caps, tells which statements to apply when.

I've added more information about the file format in the last commit.

**Comment by hwayne** [comment]
Perfecto!

**Comment by tirix** [comment]
Thank you so much!

**Pull request merged**
