### PR TITLE
Add Python implementation

### PR DESCRIPTION
**Pull request by tmcb**
Please check the `README.md` included in this PR for details.

### CODE REVIEW

**Comment by hwayne** [comment]
Unfortunately I can't accept this, since Hypothesis does property testing and not exhaustive proof.

**Comment by waldyrious** [comment]
I'm just a curious onlooker, with no formal computer science background, but I was intrigued by your observation that:

> Hypothesis does property testing and not exhaustive proof

considering that Wikipedia's article on [formal verification](https://en.wikipedia.org/wiki/Formal_verification) says (emphasis mine):

> One approach and formation is model checking, which consists of a **systematically exhaustive exploration** of the mathematical model 

...and on the other hand, the [model checking](https://en.wikipedia.org/wiki/Model_checking) article says (again, emphasis mine):

> In computer science, model checking **or property checking** is a method for checking whether a finite-state model of a system meets a given specification (also known as correctness).

Does "property checking" mean something different from what you call "property testing" above? If so, perhaps the Wikipedia article should offer that clarification to avoid ambiguity for the uninitiated.

**Comment by dhouck** [comment]
I think theyʼre the same thing (at least approximately; I donʼt know if there are subtleties).  But when Wikipedia says
> One approach and formation is model checking, which consists of a **systematically exhaustive exploration** of the mathematical model
the “exhaustive” isnʼt actually the case in some colloquial usage.

In particular, although in practice there are memory constraints, in theory a Python `list` can be arbitrarily long; as such it is *impossible* to exhaustively test leftpad in finite time.  (Given the practical memory constraints, itʼs only impossible to exhaustively test leftpad before the heat death of the universe, which is close enough).  Hypothesis is pretty good but it can miss things, which the proof methods accepted into the repository cannot (without bugs in some part of the system).

**Comment by waldyrious** [comment]
Thanks! Is there a standard name (or description/list of properties) for "the proof methods accepted into the repository"? Sorry if I'm missing something obvious! :sweat_smile:

**Comment by dhouck** [comment]
I think itʼs just a “proof” or “proving” the code (in the mathematical sense, not just the colloquial or scientific one).  You start with the assumptions about how the programming language and computer work, and the code, and you use mathematics to show 100% that if those assumptions hold then your code does what you say it does.  Iʼve heard of people working on that for Python but I havenʼt heard of a real working version.

**Comment by waldyrious** [comment]
Hmm. Considering the following passage from Wikipedia's article on [formal methods](https://en.wikipedia.org/wiki/Formal_methods):

> Automated techniques fall into three general categories:
> - [Automated theorem proving](https://en.wikipedia.org/wiki/Automated_theorem_proving), in which a system attempts to produce a formal proof from scratch, given a description of the system, a set of logical axioms, and a set of inference rules.
> - [Model checking](https://en.wikipedia.org/wiki/Model_checking), in which a system verifies certain properties by means of an exhaustive search of all possible states that a system could enter during its execution.
> - [Abstract interpretation](https://en.wikipedia.org/wiki/Abstract_interpretation), in which a system verifies an over-approximation of a behavioural property of the program, using a fixpoint computation over a (possibly complete) lattice representing it.

...would you say that all tools used in this repository should conform to the definition of a [theorem prover](https://en.wikipedia.org/wiki/Automated_theorem_proving)?

**Comment by hwayne** [comment]
I should really write a full explainer to explain to everybody what we're looking for

ACKN

**Comment by tmcb** [comment]
Hi, PR author here.

Thanks for the feedback, @hwayne.  Honestly, I only cared to check the project's commit history after submitting the PR, at which point I learned of a previous proof attempt in Python which has been removed, basically for the same reasons.

I didn't close the PR myself because I had hopes to get it converted to use [Deal's own take at formal verification](https://deal.readthedocs.io/basic/verification.html), backed by Z3 instead.  The two biggest problems I have faced are its limited support of Python's syntax and the lack of support to native functions such as `len()` and `reversed()`.

The fact that the PR sparked some discussion after being closed has motivated me to give it another try in the future.  Thank you all.

**Comment by waldyrious** [comment]
> a previous proof attempt in Python which has been removed, basically for the same reasons.

For future reference and convenience, the relevant PRs are #26, #27 and #28.

**Comment by hwayne** [comment]
yeah still need to write that explainer

**Comment by waldyrious** [comment]
> yeah still need to write that explainer

I took the liberty to open #45 to help track this :)

**Pull request closed without merging**
